# Generated by Django 2.2.3 on 2019-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeep', '0004_auto_20190710_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
